apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: music-map-backend
  namespace: music-map
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: music-map-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: music-map-frontend
  namespace: music-map
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: music-map-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
